"""Initial migration

Revision ID: b5baa9d047dc
Revises: 
Create Date: 2024-03-12 11:38:08.299783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5baa9d047dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_created_at'), 'cart', ['created_at'], unique=False)
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('featured', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_featured'), 'collection', ['featured'], unique=False)
    op.create_index(op.f('ix_collection_id'), 'collection', ['id'], unique=False)
    op.create_index(op.f('ix_collection_title'), 'collection', ['title'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_first_name'), 'customer', ['first_name'], unique=False)
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_index(op.f('ix_customer_last_name'), 'customer', ['last_name'], unique=False)
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_collection_id'), 'product', ['collection_id'], unique=False)
    op.create_index(op.f('ix_product_description'), 'product', ['description'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_inventory'), 'product', ['inventory'], unique=False)
    op.create_index(op.f('ix_product_title'), 'product', ['title'], unique=False)
    op.create_index(op.f('ix_product_unit_price'), 'product', ['unit_price'], unique=False)
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_item_cart_id'), 'cart_item', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_item_id'), 'cart_item', ['id'], unique=False)
    op.create_index(op.f('ix_cart_item_product_id'), 'cart_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_cart_item_quantity'), 'cart_item', ['quantity'], unique=False)
    op.create_table('customer_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_order_customer_id'), 'customer_order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_order_id'), 'customer_order', ['id'], unique=False)
    op.create_index(op.f('ix_customer_order_product_id'), 'customer_order', ['product_id'], unique=False)
    op.create_index(op.f('ix_customer_order_quantity'), 'customer_order', ['quantity'], unique=False)
    op.create_index(op.f('ix_customer_order_status'), 'customer_order', ['status'], unique=False)
    op.create_index(op.f('ix_customer_order_total'), 'customer_order', ['total'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_order_total'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_status'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_quantity'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_product_id'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_id'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_customer_id'), table_name='customer_order')
    op.drop_table('customer_order')
    op.drop_index(op.f('ix_cart_item_quantity'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_product_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_cart_id'), table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_index(op.f('ix_product_unit_price'), table_name='product')
    op.drop_index(op.f('ix_product_title'), table_name='product')
    op.drop_index(op.f('ix_product_inventory'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_description'), table_name='product')
    op.drop_index(op.f('ix_product_collection_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_index(op.f('ix_customer_last_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_first_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_collection_title'), table_name='collection')
    op.drop_index(op.f('ix_collection_id'), table_name='collection')
    op.drop_index(op.f('ix_collection_featured'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.drop_index(op.f('ix_cart_created_at'), table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###
